"""add_bot_logs_states_schedules_title_toggles

Revision ID: cb558cd170bd
Revises: 0013
Create Date: 2026-03-07 04:11:24.062445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb558cd170bd'
down_revision: Union[str, None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kingdom_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.String(length=1000), nullable=True),
    sa.Column('governor_id', sa.BigInteger(), nullable=True),
    sa.Column('governor_name', sa.String(length=100), nullable=True),
    sa.Column('title_type', sa.String(length=20), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kingdom_id'], ['kingdoms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_logs_action'), 'bot_logs', ['action'], unique=False)
    op.create_index(op.f('ix_bot_logs_created_at'), 'bot_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_bot_logs_id'), 'bot_logs', ['id'], unique=False)
    op.create_table('bot_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kingdom_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('scan_type', sa.String(length=20), nullable=True),
    sa.Column('scan_options', sa.String(length=2000), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kingdom_id'], ['kingdoms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kingdom_id')
    )
    op.create_index(op.f('ix_bot_states_id'), 'bot_states', ['id'], unique=False)
    op.create_table('scheduled_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kingdom_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=30), nullable=False),
    sa.Column('scan_type', sa.String(length=20), nullable=True),
    sa.Column('cron_expr', sa.String(length=50), nullable=True),
    sa.Column('interval_hours', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kingdom_id'], ['kingdoms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_tasks_id'), 'scheduled_tasks', ['id'], unique=False)
    op.add_column('governor_profiles', sa.Column('t1_deaths', sa.BigInteger(), nullable=True))
    op.add_column('governor_profiles', sa.Column('t2_deaths', sa.BigInteger(), nullable=True))
    op.add_column('governor_profiles', sa.Column('t3_deaths', sa.BigInteger(), nullable=True))
    op.add_column('governor_profiles', sa.Column('t4_deaths', sa.BigInteger(), nullable=True))
    op.add_column('governor_profiles', sa.Column('t5_deaths', sa.BigInteger(), nullable=True))
    op.add_column('governor_profiles', sa.Column('victories', sa.BigInteger(), nullable=True))
    op.add_column('governor_profiles', sa.Column('defeats', sa.BigInteger(), nullable=True))
    op.add_column('governor_profiles', sa.Column('scout_times', sa.BigInteger(), nullable=True))
    op.add_column('governor_profiles', sa.Column('healed', sa.BigInteger(), nullable=True))
    op.add_column('governor_profiles', sa.Column('civilization', sa.String(length=30), nullable=True))
    op.add_column('governor_snapshots', sa.Column('t1_deaths', sa.BigInteger(), nullable=True))
    op.add_column('governor_snapshots', sa.Column('t2_deaths', sa.BigInteger(), nullable=True))
    op.add_column('governor_snapshots', sa.Column('t3_deaths', sa.BigInteger(), nullable=True))
    op.add_column('governor_snapshots', sa.Column('t4_deaths', sa.BigInteger(), nullable=True))
    op.add_column('governor_snapshots', sa.Column('t5_deaths', sa.BigInteger(), nullable=True))
    op.add_column('governor_snapshots', sa.Column('victories', sa.BigInteger(), nullable=True))
    op.add_column('governor_snapshots', sa.Column('defeats', sa.BigInteger(), nullable=True))
    op.add_column('governor_snapshots', sa.Column('scout_times', sa.BigInteger(), nullable=True))
    op.add_column('governor_snapshots', sa.Column('healed', sa.BigInteger(), nullable=True))
    op.add_column('title_bot_settings', sa.Column('enable_scientist', sa.Boolean(), nullable=True))
    op.add_column('title_bot_settings', sa.Column('enable_duke', sa.Boolean(), nullable=True))
    op.add_column('title_bot_settings', sa.Column('enable_architect', sa.Boolean(), nullable=True))
    op.add_column('title_bot_settings', sa.Column('enable_justice', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('title_bot_settings', 'enable_justice')
    op.drop_column('title_bot_settings', 'enable_architect')
    op.drop_column('title_bot_settings', 'enable_duke')
    op.drop_column('title_bot_settings', 'enable_scientist')
    op.drop_column('governor_snapshots', 'healed')
    op.drop_column('governor_snapshots', 'scout_times')
    op.drop_column('governor_snapshots', 'defeats')
    op.drop_column('governor_snapshots', 'victories')
    op.drop_column('governor_snapshots', 't5_deaths')
    op.drop_column('governor_snapshots', 't4_deaths')
    op.drop_column('governor_snapshots', 't3_deaths')
    op.drop_column('governor_snapshots', 't2_deaths')
    op.drop_column('governor_snapshots', 't1_deaths')
    op.drop_column('governor_profiles', 'civilization')
    op.drop_column('governor_profiles', 'healed')
    op.drop_column('governor_profiles', 'scout_times')
    op.drop_column('governor_profiles', 'defeats')
    op.drop_column('governor_profiles', 'victories')
    op.drop_column('governor_profiles', 't5_deaths')
    op.drop_column('governor_profiles', 't4_deaths')
    op.drop_column('governor_profiles', 't3_deaths')
    op.drop_column('governor_profiles', 't2_deaths')
    op.drop_column('governor_profiles', 't1_deaths')
    op.drop_index(op.f('ix_scheduled_tasks_id'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_index(op.f('ix_bot_states_id'), table_name='bot_states')
    op.drop_table('bot_states')
    op.drop_index(op.f('ix_bot_logs_id'), table_name='bot_logs')
    op.drop_index(op.f('ix_bot_logs_created_at'), table_name='bot_logs')
    op.drop_index(op.f('ix_bot_logs_action'), table_name='bot_logs')
    op.drop_table('bot_logs')
    # ### end Alembic commands ###
